# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bosques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bosque',
            name='id_arbol',
        ),
        migrations.AddField(
            model_name='arbol',
            name='id_bosque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bosques.Bosque'),
        ),
    ]
