# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosques', '0002_auto_20190723_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbol',
            old_name='id_bosque',
            new_name='id_forest',
        ),
    ]
